name: Deploy to S3 + CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          echo "🚀 Starting S3 deployment..."
          
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".gitignore" \
            --exclude "*.md" \
            --exclude ".replit"
          
          echo "✅ S3 deployment completed"

      - name: Verify S3 Deployment
        run: |
          echo "🔍 Verifying S3 deployment..."
          aws s3api head-object --bucket ${{ secrets.S3_BUCKET_NAME }} --key index.html >/dev/null 2>&1 || (echo "❌ S3 deployment failed" && exit 1)
          echo "✅ S3 deployment verified"

      - name: Invalidate CloudFront cache
        run: |
          echo "🔄 Starting CloudFront cache invalidation..."
          
          INVALIDATION_ID=$(aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*" \
            --query 'Invalidation.Id' \
            --output text)
          
          echo "📋 Invalidation ID: $INVALIDATION_ID"
          echo "⏳ Waiting for invalidation to complete..."
          
          aws cloudfront wait invalidation-completed \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --id $INVALIDATION_ID \
            --cli-read-timeout 300 \
            --cli-connect-timeout 60
          
          echo "✅ CloudFront cache invalidation completed successfully"